Semaphore
Konkuk-Grad/Microbench pull request #24
Opened 2020-08-19 06:01 UTC by jjangsean

testing 하던 중 발견된 fork()의 오류를 해결하였습니다.
shared memory를 활용하여 프로세스의 시간을 모두 받아올 수 있게 수정하였습니다.
.c의 이름 또한 다른 토폴로지와 비교될 수 있도록 _pp를 붙였습니다.
testing을 위해 임의로 cmakelist.txt를 변경하였습니다.
추후 이 점이 문제될 수 있으니 수정시 고려 부탁드립니다.
이전과는 다르게 mbti_main.c에서 동작할 수 있도록 하였습니다.

2020-08-19 06:29 UTC, EmptyPaper commented on mbti/mbti_semaphore/mbti_sem.h
> +int sem_buffer[1], sem_front, sem_rear,shm_id;
buffer 를 좀더 크게 하는게 좀 더 여러케이스에서 차이를 볼 수 있을거 같에요.
예를 들어 버퍼를 크게하면 Cach affinity도 생기고 여러 부가 요소들이 생기거든요

2020-08-19 06:29 UTC, EmptyPaper commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +            perror("fork error");
종료하는것도 나쁘지 않을것 같습니다.

2020-08-19 06:29 UTC, EmptyPaper commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +	free(pid);
pid 말고 다른 할당 해제할 변수들은 없나요?

2020-08-19 06:35 UTC, s5kywa1k3r requested changes

2020-08-19 06:35 UTC, s5kywa1k3r commented on mbti/CMakeLists.txt
> +aux_source_directory(mbti_semaphore SEM_SRC)
issue 답변을 보고 수정하여 pull request를 날리려 했으나 현 코드대로 만들 예정이었고, 특이사항 없는 점 확인하였습니다.
단지 추후에 고려되어야 하는것들은 나머지 인원 (@EmptyPaper @spark-1 ) 분들이 해당 폴더에서 작업을 안하실 경우 추가적으로 수정하여야할 요소가 있습니다.

2020-08-19 06:35 UTC, s5kywa1k3r commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +	result = pthread_setaffinity_np(current_thread, sizeof(cpu_set_t), &cpuset);
코어 설정 부분 확인하였습니다.

2020-08-19 06:35 UTC, s5kywa1k3r commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +			make_shm();
이미 생성된 공유메모리에 접근하기 위해 이러한 작업을 다시 진행하는 건가요? shm_id나 shm_addr은 전역변수이고 부모에서 make_shm을 하였을 때 이미 생성되어 다시 추가적으로 생성할 필요가 없다는 생각이 드는데요.

2020-08-19 06:35 UTC, s5kywa1k3r commented on mbti/mbti_semaphore/mbti_sem_pp.c
>  			//느린 시스템콜로 인해 비정상 종료되는 상황을 방지
느린 시스템 콜로 인해 비정상 종료되는 상황이라는 말이 사실 이해가 잘 되지 않습니다.

2020-08-19 06:35 UTC, s5kywa1k3r commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +		if(pid[i] > 0)
이 if문은 자식에서 이미 exit(0)를 하여 종료가 되었을 것이고 부모만 for문을 돌게 될 것인데 pid[i] > 0임을 확인하는 것은 자식이 한번도 하지 않을 것으로 생각됩니다.

2020-08-19 06:39 UTC, EmptyPaper commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +			make_shm();
각 페어마다 만드는거 같은데 테스트 결과에 큰 영향은 없겠지만 페어가 많아지면  프로그렘의 안정성 문제도 생길것 같습니다.

2020-08-19 06:39 UTC, jjangsean commented
가끔 자식이 종료되기 전에 시스템콜 응답이 느려져서 자동으로 종료되는 현상이 있다고 합니다.
느린 시스템콜이라고 쓴 부분은 이것을 해결하기 위함입니다.
실제로 저 부분을 지운 후 테스트시 오류가 발생하였습니다.

2020-08-19 06:43 UTC, jjangsean commented
공유 메모리 구현시 참고한 사이트의 접근법을 따른 것인데 문제가 생기는 부분이라면 삭제하도록 하겠습니다.
지운 후 테스트 시, 별다른 문제는 없었으나. 접근을 위해 사용하는 것이라고 생각하여 남겨두었었습니다. 추후 수정하겠습니다

2020-08-19 07:25 UTC, jjangsean commented on mbti/mbti_semaphore/mbti_sem.h
> +int sem_buffer[1], sem_front, sem_rear,shm_id;
1024까지 올리겠습니다.
cach affinity 부분은 이후 회의에서 설명해주세요

2020-08-19 07:25 UTC, jjangsean commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +            perror("fork error");
종료 메시지를 함께 넣도록 하겠습니다.

2020-08-19 07:26 UTC, jjangsean commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +	free(pid);
동적할당은 pid만 하고 있습니다.

2020-08-19 07:26 UTC, jjangsean commented on mbti/CMakeLists.txt
> +aux_source_directory(mbti_semaphore SEM_SRC)
네 알겠습니다.

2020-08-19 07:26 UTC, jjangsean commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +			make_shm();
공유 메모리 구현시 참고한 사이트의 접근법을 따른 것인데 문제가 생기는 부분이라면 삭제하도록 하겠습니다.
지운 후 테스트 시, 별다른 문제는 없었으나. 접근을 위해 사용하는 것이라고 생각하여 남겨두었었습니다. 추후 수정하겠습니다

2020-08-19 07:32 UTC, jjangsean commented on mbti/mbti_semaphore/mbti_sem_pp.c
> +		if(pid[i] > 0)
굳이 부모임을 확인할 필요가 없다는 것이군요! 해당 if문을 삭제하도록 하겠습니다.

2020-08-19 07:51 UTC, s5kywa1k3r approved these changes

2020-08-20 07:59 UTC, spark-1 approved these changes

2020-08-20 08:44 UTC, EmptyPaper approved these changes

2020-08-20 08:45 UTC, merged